// <auto-generated />
using ExpenseMVC.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ExpenseMVC.Models
{
    [DbContext(typeof(DataProtectionContext))]
    public partial class DataProtectionContextModel : RuntimeModel
    {
        static DataProtectionContextModel()
        {
            var model = new DataProtectionContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DataProtectionContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
